@startuml AncillaryBlocks
/'
> 2019-12-06
    - added alt attribute to LiteralBlock
'/


'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class BasicBlock {
}

class FigureBlock{
    +source: String[0..1]
    +unnumbered: Boolean[0..1]
    +subsequence: String[0..1]
    +name: TextElement[0..*]
    +class: LocalizedString[0..1]
    +image: Image[0..1]
    +video: Video[0..1]
    +audio: Audio[0..1]
    +figure: Subfigure[0..*]
    +definitions: DefinitionList[0..1]
    +footnotes: ReferenceToldWithParagraphElement[0..*]
}

class Subfigure {
}

class SourcecodeBlock{
    +name: TextElement[0..*]
    +unnumbered: Boolean[0..1]
    +subsequence: String[0..1]
    +filename: String[0..1]
    +lang: String[0..1]
    +content: String
    +callouts: ReferenceToIdElement[0..*]
    +calloutAnnotations[0..*]: ParagraphBlock[0..*]
}

class FormulaBlock{
    +stem: StemElement
    +unnumbered: Boolean[0..1]
    +subsequence: String[0..1]
    +inequality: Boolean[0..1]
    +definitions: DefinitionList[0..1]
}

class ExampleBlock{
    +name: TextElement[0..*]
    +unnumbered: Boolean[0..1]
    +subsequence: String[0..1]
    +formula: StemElement[0..*]
    +lists: UnorderedList[0..*]
    +quotes: QuoteBlock[0..*]
    +sourcecode: SourcecodeBlock[0..*]
    +paragraphs: ParagraphWithFootnote[0..*]
}

class LiteralBlock{
    +alt[0..1]: String
}


'******* NOTES *******************************************************
note left of Subfigure : Subfigures and images\nonly occur\nwithin figures

'******* CLASS RELATIONS *********************************************
FigureBlock -up-|> BasicBlock
LiteralBlock -up-|> BasicBlock
SourcecodeBlock -up-|> BasicBlock
FormulaBlock -up-|> BasicBlock
ExampleBlock -up-|> BasicBlock

Subfigure -up-|> FigureBlock

@enduml
