@startuml DataTypes

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class LocalizedString {
    +language: Iso639Code[0..*]
    +script: Iso15924Code[0..*]
    +content: String
}

class Uri <<dataType>> {

}

class String <<primitiveType>> {

}

class FormattedString {
    +format: StringFormat = "plain"
}

class Iso8601DateTime <<dataType>> {

}

class Iso15924Code <<dataType>> {

}

class Iso639Code <<dataType>> {

}

enum StringFormat <<enumeration>> {
    plain
    html
    docbook
    tei
    asciidoc
    markdown
    standarddoc
    isodoc
}


'******* NOTES *******************************************************
note bottom of FormattedString: FormattedString\ndefaults to "plain"
note bottom of StringFormat: The coresponsind MIME types,\ndefaults to "text/plain"\n(docbook / asciidoc / isdoc\nare not registered types yet)


'******* CLASS RELATIONS *********************************************
LocalizedString <|-- FormattedString
FormattedString <-- StringFormat

@enduml