@startuml EmptyElements

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class BasicElement{
}

class PageBreakElement{

}

class LineBreakElement{

}

class HorizontalRuleElement{

}

class IndexElement {
    +primary: String
    +secondary: String[0..1]
    +tertiary: String[0..1]
}

class IndexXrefElement {
    +primary: String
    +secondary: String[0..1]
    +tertiary: String[0..1]
    +target: String[0..1]
    +also: Boolean
}

'******* NOTES *******************************************************
note "* `LinkBreakElement` is `<br>`\n* `HorizontalRuleElement` is `<hr>`\n* `PageBreakElement` only works in page layout\n(e.g., PDF, Word), not in flow layouts (e.g., HTML)" as N1


'******* CLASS RELATIONS *********************************************
BasicElement <|-down- PageBreakElement
BasicElement <|-down- LineBreakElement
BasicElement <|-down- HorizontalRuleElement
BasicElement <|-down- IndexElement
BasicElement <|-down- IndexXrefElement

@enduml
