@startuml EmptyElements

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class BasicElement{
}

class PageBreakElement{

}

class LineBreakElement{

}

class HorizontalRuleElement{

}

'******* NOTES *******************************************************
note "* `LinkBreakElement` is `<br>`\n* `HorizontalRuleElement` is `<hr>`\n* `PageBreakElement` only works in page layout\n(e.g., PDF, Word), not in flow layouts (e.g., HTML)" as N1


'******* CLASS RELATIONS *********************************************
BasicElement <|-down- PageBreakElement
BasicElement <|-down- LineBreakElement
BasicElement <|-down- HorizontalRuleElement

@enduml
