@startuml IdElements
/'
Diagram:        IdElements
DateCreate:     28/07/2018
Description:    BasicDocument / SecureDoc is a family of document models that forms the basis of Metanorma IsoDoc (via Metanorma StandardDocument), which is used to represent ISO Standards and similarly structured standards.
                It is also the document model that Selagraph operates on.
                The Relaton Bibliography UML models used in these models are located here: Relaton BibModels.
                BasicDocument itself is a document model that can serve as a transit data structure for document conversion, such as taking input from AsciiDoc or Markdown and converting them into an output format, such as Metanorma IsoDoc

Hystory of changes:
> 22/08/2018
    - diagram configuration updated
    - new classes are added "Bookmark"
    - classes are removed/commented "Figure", "Subfigure", "List", "UnorderedList", "DefinitionList", "OrderedList", "Definition"
    - enumerations are removed/commented "OrderedListType"
    - notes are added for "Image"
    - some of the relations between the elements are updated
> 18/01/2019
    - alt attribute on images
> 19/03/2019
    - added image/filename
> 14/10/2019
    - added title attribute on media
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class BasicElement {
    +contribMetadata: ContributionElementMetadata[0..*]
}

class IdElement{
    +id: String
}

class Media{
    +filename[0..1]: String
    +source: Uri
    +type: MediaType
    +alt[0..1]: String
    +title[0..1]: String
    +longdesc[0..1]: Uri
}

class Image{
    +height[0..1]: Integer
    +width[0..1]: Integer
}

class Audio{
    +altsource[0..*]: AltSource
}

class Video{
    +altsource[0..*]: AltSource
    +height[0..1]: Integer
    +width[0..1]: Integer
}

class AltSource{
    +filename[0..1]: String
    +source: Uri
    +type: MediaType
}

class Bookmark{

}

/'
class Figure{
    +source: String[0..1]
    +name: LocalizedString[0..1]
    +note: ParagraphWithFootnote[0..*]
    +figure: Subfigure[0..*]
    +definitions: DefinitionList[0..1]
    +image: Image[0..1]
    +footnotes: ReferenceToldWithParagraphElement[0..*]
}

class Subfigure{

}

class List{
    +listItem
}

class UnorderedList{
    +listItem: ParagraphWithFootnote[0..*]
}

class DefinitionList{
    +listItem: Definition[0..*]
}

class OrderedList{
    +type: OrderedListType
}

class Definition{
    +term: LocalizedString
    +definition: ParagraphWithFootnote[0..*]
}
'/

class MediaType{
    +content: String
}

/'
enum OrderedListType <<enumeration>>{
    roman
    alphabet
    arabic
    roman_upper
    alphabet_upper
}
'/

'******* NOTES *******************************************************
note right of IdElement : The `IdElement` itself acts as a reference point,\nsuch as in a SourcecodeBlock for\ncallout references (the IdElement is the location),\nand for delimiting ReviewComment start/end places.
note left of Image : We also allow the\nvalue "auto" for\nheight and width
'note bottom of Subfigure : Subfigures and images\nonly occur within figures
'note right of Image: "filename" is where the image file may be extracted to\nin downstream processing,\nas distinct from the image source.
note right of MediaType : MIME types recommended

'******* CLASS RELATIONS *********************************************
BasicElement <|-- IdElement

IdElement <|-- Media
IdElement <|-- Bookmark
Media <|-- Image
Media <|-- Audio
Media <|-- Video

Media <-- MediaType
Video <-- AltSource
Audio <-- AltSource


/'
IdElement <|-- Figure
IdElement <|-- List

Figure <|-- Subfigure

List <|-- UnorderedList
List <|-- DefinitionList

DefinitionList <-- Definition

UnorderedList <|-- OrderedList

OrderedList <-- OrderedListType
'/

@enduml
