@startuml Paragraphs

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BasicBlock {
}

class ParagraphBlock{
    +contents: BasicElement[0..*]
    +alignment: TextAlignment[0..1]
}

class ParagraphsBlock{
    +contents: ParagraphWithFootnote[0..*]
}

class ParagraphWithFootnote{
    +footnotes: ReferenceToldWithParagraphElement[0..*]
}

enum TextAlignment <<enumeration>>{
    left
    center
    right
    justified
}

'******* NOTES *******************************************************

'******* CLASS RELATIONS *********************************************
BasicBlock <|-- ParagraphBlock
BasicBlock <|-- ParagraphsBlock

ParagraphBlock <|-- ParagraphWithFootnote
ParagraphBlock <-- TextAlignment

@enduml
